### ISSUE TITLE
RuntimeError: Tensor type unknown to einops <class 'str'>

### ISSUE THREAD

**Issue by xindiw99** [Make-A-Protagonist/Make-A-Protagonist#12]
Hi, 

Thanks for this repo! I want to ask whether you've encountered the following error before? Thank you!

```
Traceback (most recent call last):                                                                                                                                   | 0/50 [00:00<?, ?it/s]
  File "/data/home/xindiw/miniconda3/envs/tune/lib/python3.9/pdb.py", line 1726, in main
    pdb._runscript(mainpyfile)
  File "/data/home/xindiw/miniconda3/envs/tune/lib/python3.9/pdb.py", line 1586, in _runscript
    self.run(statement)
  File "/data/home/xindiw/miniconda3/envs/tune/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/data/home/xindiw/Make-A-Protagonist/train.py", line 1, in <module>
    import argparse
  File "/data/home/xindiw/Make-A-Protagonist/train.py", line 470, in main
    sample = validation_pipeline(image=_ref_image, prompt=prompt, control_image=conditions, generator=generator, latents=ddim_inv_latent, image_embeds=image_embed, masks=masks, prior_latents=prior_embeds, prior_denoised_embeds=prior_denoised_embeds, **validation_data).videos
  File "/data/home/xindiw/miniconda3/envs/tune/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/data/home/xindiw/Make-A-Protagonist/makeaprotagonist/pipelines/pipeline_stable_unclip_controlavideo.py", line 1433, in __call__
    down_block_res_samples = [rearrange(sample, "(b f) c h w -> b c f h w", f=video_length) for sample in down_block_res_samples]
  File "/data/home/xindiw/Make-A-Protagonist/makeaprotagonist/pipelines/pipeline_stable_unclip_controlavideo.py", line 1433, in <listcomp>
    down_block_res_samples = [rearrange(sample, "(b f) c h w -> b c f h w", f=video_length) for sample in down_block_res_samples]
  File "/data/home/xindiw/miniconda3/envs/tune/lib/python3.9/site-packages/einops/einops.py", line 483, in rearrange
    return reduce(cast(Tensor, tensor), pattern, reduction='rearrange', **axes_lengths)
  File "/data/home/xindiw/miniconda3/envs/tune/lib/python3.9/site-packages/einops/einops.py", line 412, in reduce
    return _apply_recipe(recipe, tensor, reduction_type=reduction)
  File "/data/home/xindiw/miniconda3/envs/tune/lib/python3.9/site-packages/einops/einops.py", line 233, in _apply_recipe
    backend = get_backend(tensor)
  File "/data/home/xindiw/miniconda3/envs/tune/lib/python3.9/site-packages/einops/_backends.py", line 52, in get_backend
    raise RuntimeError('Tensor type unknown to einops {}'.format(type(tensor)))
RuntimeError: Tensor type unknown to einops <class 'str'>
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /data/home/xindiw/miniconda3/envs/tune/lib/python3.9/site-packages/einops/_backends.py(52)get_backend()
-> raise RuntimeError('Tensor type unknown to einops {}'.format(type(tensor)))
```

**Comment by HeliosZhao** [comment]
Hi, it is a problem of `diffusers`. You can solve this by `pip install diffusers==0.15.1`

**Comment by xindiw99** [comment]
Thank you! It works now, really appreciate it!!
