### ISSUE TITLE
after running "python eval.py --config="configs/<video_name>/eval.yaml"",Attention object argument after ** must be a mapping, not bool

### ISSUE THREAD

**Issue by MnKnight1** [Make-A-Protagonist/Make-A-Protagonist#21]

**Comment by MnKnight1** [comment]
after running "python eval.py --config="configs/<video_name>/eval.yaml"",

Traceback (most recent call last):
  File "eval.py", line 368, in <module>
    main(**config)
  File "eval.py", line 325, in main
    sample = validation_pipeline(image=_ref_image, prompt=prompt, control_image=conditions, generator=generator, latents=ddim_inv_latent, image_embeds=image_embed, noise_level=v_noise, masks=masks, prior_latents=prior_embeds, prior_denoised_embeds=prior_denoised_embeds, **validation_data).videos
  File "/home/litaiqing/anaconda3/envs/diff/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/media/ssd_1/litaiqing/Make-A-Protagonist/makeaprotagonist/pipelines/pipeline_stable_unclip_controlavideo.py", line 1421, in __call__
    down_block_res_samples, mid_block_res_sample = self.controlnet(
  File "/home/litaiqing/anaconda3/envs/diff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/ssd_1/litaiqing/Make-A-Protagonist/makeaprotagonist/pipelines/pipeline_stable_unclip_controlavideo.py", line 121, in forward
    down_samples, mid_sample = controlnet(
  File "/home/litaiqing/anaconda3/envs/diff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/litaiqing/anaconda3/envs/diff/lib/python3.8/site-packages/diffusers/models/controlnet.py", line 761, in forward
    sample, res_samples = downsample_block(
  File "/home/litaiqing/anaconda3/envs/diff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/litaiqing/anaconda3/envs/diff/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 996, in forward
    hidden_states = attn(
  File "/home/litaiqing/anaconda3/envs/diff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/litaiqing/anaconda3/envs/diff/lib/python3.8/site-packages/diffusers/models/transformer_2d.py", line 291, in forward
    hidden_states = block(
  File "/home/litaiqing/anaconda3/envs/diff/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/litaiqing/anaconda3/envs/diff/lib/python3.8/site-packages/diffusers/models/attention.py", line 154, in forward
    attn_output = self.attn1(
TypeError: Attention object argument after ** must be a mapping, not bool

**Comment by HeliosZhao** [comment]
May I know the version of `diffusers` you use? We use `diffusers==0.15.1` in our code.

**Comment by MnKnight1** [comment]
> May I know the version of `diffusers` you use? We use `diffusers==0.15.1` in our code.

I use diffusers==0.19.0

**Comment by HeliosZhao** [comment]
You may try `diffusers==0.15.1`. Later version changes the source code for ControlNet.

**Comment by MnKnight1** [comment]
> You may try `diffusers==0.15.1`. Later version changes the source code for ControlNet.

Okay, thank you very much. 
It is due to the problem with the diffusers version.
