### ISSUE TITLE
name '_C' is not defined

### ISSUE THREAD

**Issue by Laidawang** [Make-A-Protagonist/Make-A-Protagonist#6]
when i try the test: i got
`python experts/grounded_sam_inference.py -d data/ikun/images/0000.jpg -t "a man with a basketball"`
`/data2/home/srchen/project/github/in_work/Make-A-Protagonist/experts/GroundedSAM/GroundingDINO/groundingdino/models/GroundingDINO/ms_deform_attn.py:31: UserWarning: Failed to load custom C++ ops. Running on CPU mode Only!
  warnings.warn("Failed to load custom C++ ops. Running on CPU mode Only!")
/root/miniconda3/envs/make_a_ptotagonist/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3483.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
final text_encoder_type: bert-base-uncased
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
_IncompatibleKeys(missing_keys=[], unexpected_keys=['label_enc.weight'])
  0%|                                                                                                           | 0/1 [00:00<?, ?it/s]/root/miniconda3/envs/make_a_ptotagonist/lib/python3.9/site-packages/transformers/modeling_utils.py:866: FutureWarning: The `device` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
/root/miniconda3/envs/make_a_ptotagonist/lib/python3.9/site-packages/torch/utils/checkpoint.py:31: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
  0%|                                                                                                           | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/data2/home/srchen/project/github/in_work/Make-A-Protagonist/experts/grounded_sam_inference.py", line 208, in <module>
    boxes_filt, pred_phrases, logits_filt = get_grounding_output(
  File "/data2/home/srchen/project/github/in_work/Make-A-Protagonist/experts/grounded_sam_inference.py", line 72, in get_grounding_output
    outputs = model(image[None], captions=[caption])
  File "/root/miniconda3/envs/make_a_ptotagonist/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/home/srchen/project/github/in_work/Make-A-Protagonist/experts/GroundedSAM/GroundingDINO/groundingdino/models/GroundingDINO/groundingdino.py", line 313, in forward
    hs, reference, hs_enc, ref_enc, init_box_proposal = self.transformer(
  File "/root/miniconda3/envs/make_a_ptotagonist/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/home/srchen/project/github/in_work/Make-A-Protagonist/experts/GroundedSAM/GroundingDINO/groundingdino/models/GroundingDINO/transformer.py", line 258, in forward
    memory, memory_text = self.encoder(
  File "/root/miniconda3/envs/make_a_ptotagonist/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/home/srchen/project/github/in_work/Make-A-Protagonist/experts/GroundedSAM/GroundingDINO/groundingdino/models/GroundingDINO/transformer.py", line 576, in forward
    output = checkpoint.checkpoint(
  File "/root/miniconda3/envs/make_a_ptotagonist/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/root/miniconda3/envs/make_a_ptotagonist/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/root/miniconda3/envs/make_a_ptotagonist/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/root/miniconda3/envs/make_a_ptotagonist/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/home/srchen/project/github/in_work/Make-A-Protagonist/experts/GroundedSAM/GroundingDINO/groundingdino/models/GroundingDINO/transformer.py", line 785, in forward
    src2 = self.self_attn(
  File "/root/miniconda3/envs/make_a_ptotagonist/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/home/srchen/project/github/in_work/Make-A-Protagonist/experts/GroundedSAM/GroundingDINO/groundingdino/models/GroundingDINO/ms_deform_attn.py", line 338, in forward
    output = MultiScaleDeformableAttnFunction.apply(
  File "/root/miniconda3/envs/make_a_ptotagonist/lib/python3.9/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/data2/home/srchen/project/github/in_work/Make-A-Protagonist/experts/GroundedSAM/GroundingDINO/groundingdino/models/GroundingDINO/ms_deform_attn.py", line 53, in forward
    output = _C.ms_deform_attn_forward(
NameError: name '_C' is not defined`

**Comment by huytuong010101** [comment]
This error due to your GroundingDINO building without nvcc
`export CUDA_VISIBLE_DEVICES=-1` solved this problem (Inferrence on CPU only)

**Comment by Laidawang** [comment]
yes, thx

**Comment by HeliosZhao** [comment]
Thanks @huytuong010101 for the reply!

@Laidawang  I didn't encounter this before. You could try to rebuild GroundedSAM or use CPU inference.

BTW, GroundingDINO detects bounding boxes for each noun in the sentence, so it is better to use only one noun. For example, use `-t man` here.
